name: Deploy
on: [push, workflow_dispatch]
jobs:
  build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop

    - uses: actions/download-artifact@develop
      with:
        name: dist-jassboard
        path: dist

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: dist/