name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [develop, main]
    types: 
      - completed
jobs:
  build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@master
      with:
        name: dist-jassboard
        path: dist

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: dist/